var annotated_dup =
[
    [ "Catch", null, [
      [ "Detail", null, [
        [ "Approx", "class_catch_1_1_detail_1_1_approx.html", null ],
        [ "EnumInfo", "struct_catch_1_1_detail_1_1_enum_info.html", null ],
        [ "IsStreamInsertable", "class_catch_1_1_detail_1_1_is_stream_insertable.html", null ]
      ] ],
      [ "detail", null, [
        [ "is_range_impl", "struct_catch_1_1detail_1_1is__range__impl.html", null ],
        [ "is_range_impl< T, typename void_type< decltype(begin(std::declval< T >()))>::type >", "struct_catch_1_1detail_1_1is__range__impl_3_01_t_00_01typename_01void__type_3_01decltype_07begin8604ecb9de16ea7789f2f694ac896ffd.html", null ],
        [ "void_type", "struct_catch_1_1detail_1_1void__type.html", null ]
      ] ],
      [ "Generators", null, [
        [ "as", "struct_catch_1_1_generators_1_1as.html", null ],
        [ "ChunkGenerator", "class_catch_1_1_generators_1_1_chunk_generator.html", null ],
        [ "FilterGenerator", "class_catch_1_1_generators_1_1_filter_generator.html", null ],
        [ "FixedValuesGenerator", "class_catch_1_1_generators_1_1_fixed_values_generator.html", null ],
        [ "Generators", "class_catch_1_1_generators_1_1_generators.html", null ],
        [ "GeneratorUntypedBase", "class_catch_1_1_generators_1_1_generator_untyped_base.html", null ],
        [ "GeneratorWrapper", "class_catch_1_1_generators_1_1_generator_wrapper.html", null ],
        [ "IGenerator", "struct_catch_1_1_generators_1_1_i_generator.html", null ],
        [ "IteratorGenerator", "class_catch_1_1_generators_1_1_iterator_generator.html", null ],
        [ "MapGenerator", "class_catch_1_1_generators_1_1_map_generator.html", null ],
        [ "RandomFloatingGenerator", "class_catch_1_1_generators_1_1_random_floating_generator.html", null ],
        [ "RandomIntegerGenerator", "class_catch_1_1_generators_1_1_random_integer_generator.html", null ],
        [ "RangeGenerator", "class_catch_1_1_generators_1_1_range_generator.html", null ],
        [ "RepeatGenerator", "class_catch_1_1_generators_1_1_repeat_generator.html", null ],
        [ "SingleValueGenerator", "class_catch_1_1_generators_1_1_single_value_generator.html", null ],
        [ "TakeGenerator", "class_catch_1_1_generators_1_1_take_generator.html", null ]
      ] ],
      [ "Matchers", null, [
        [ "Exception", null, [
          [ "ExceptionMessageMatcher", "class_catch_1_1_matchers_1_1_exception_1_1_exception_message_matcher.html", null ]
        ] ],
        [ "Floating", null, [
          [ "WithinAbsMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_abs_matcher.html", null ],
          [ "WithinRelMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_rel_matcher.html", null ],
          [ "WithinUlpsMatcher", "struct_catch_1_1_matchers_1_1_floating_1_1_within_ulps_matcher.html", null ]
        ] ],
        [ "Generic", null, [
          [ "PredicateMatcher", "class_catch_1_1_matchers_1_1_generic_1_1_predicate_matcher.html", null ]
        ] ],
        [ "Impl", null, [
          [ "MatchAllOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_all_of.html", null ],
          [ "MatchAnyOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_any_of.html", null ],
          [ "MatcherBase", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_base.html", null ],
          [ "MatcherMethod", "struct_catch_1_1_matchers_1_1_impl_1_1_matcher_method.html", null ],
          [ "MatcherUntypedBase", "class_catch_1_1_matchers_1_1_impl_1_1_matcher_untyped_base.html", null ],
          [ "MatchNotOf", "struct_catch_1_1_matchers_1_1_impl_1_1_match_not_of.html", null ]
        ] ],
        [ "StdString", null, [
          [ "CasedString", "struct_catch_1_1_matchers_1_1_std_string_1_1_cased_string.html", null ],
          [ "ContainsMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_contains_matcher.html", null ],
          [ "EndsWithMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_ends_with_matcher.html", null ],
          [ "EqualsMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_equals_matcher.html", null ],
          [ "RegexMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_regex_matcher.html", null ],
          [ "StartsWithMatcher", "struct_catch_1_1_matchers_1_1_std_string_1_1_starts_with_matcher.html", null ],
          [ "StringMatcherBase", "struct_catch_1_1_matchers_1_1_std_string_1_1_string_matcher_base.html", null ]
        ] ],
        [ "Vector", null, [
          [ "ApproxMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_approx_matcher.html", null ],
          [ "ContainsElementMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_element_matcher.html", null ],
          [ "ContainsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_contains_matcher.html", null ],
          [ "EqualsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_equals_matcher.html", null ],
          [ "UnorderedEqualsMatcher", "struct_catch_1_1_matchers_1_1_vector_1_1_unordered_equals_matcher.html", null ]
        ] ]
      ] ],
      [ "always_false", "struct_catch_1_1always__false.html", null ],
      [ "AssertionHandler", "class_catch_1_1_assertion_handler.html", null ],
      [ "AssertionInfo", "struct_catch_1_1_assertion_info.html", null ],
      [ "AssertionReaction", "struct_catch_1_1_assertion_reaction.html", null ],
      [ "AutoReg", "struct_catch_1_1_auto_reg.html", null ],
      [ "BinaryExpr", "class_catch_1_1_binary_expr.html", null ],
      [ "Capturer", "class_catch_1_1_capturer.html", null ],
      [ "CaseSensitive", "struct_catch_1_1_case_sensitive.html", null ],
      [ "Counts", "struct_catch_1_1_counts.html", null ],
      [ "Decomposer", "struct_catch_1_1_decomposer.html", null ],
      [ "ExceptionTranslatorRegistrar", "class_catch_1_1_exception_translator_registrar.html", null ],
      [ "ExprLhs", "class_catch_1_1_expr_lhs.html", null ],
      [ "GeneratorException", "class_catch_1_1_generator_exception.html", null ],
      [ "IConfig", "struct_catch_1_1_i_config.html", null ],
      [ "IContext", "struct_catch_1_1_i_context.html", null ],
      [ "IExceptionTranslator", "struct_catch_1_1_i_exception_translator.html", null ],
      [ "IExceptionTranslatorRegistry", "struct_catch_1_1_i_exception_translator_registry.html", null ],
      [ "IGeneratorTracker", "struct_catch_1_1_i_generator_tracker.html", null ],
      [ "IMutableContext", "struct_catch_1_1_i_mutable_context.html", null ],
      [ "IMutableEnumValuesRegistry", "struct_catch_1_1_i_mutable_enum_values_registry.html", null ],
      [ "IMutableRegistryHub", "struct_catch_1_1_i_mutable_registry_hub.html", null ],
      [ "IRegistryHub", "struct_catch_1_1_i_registry_hub.html", null ],
      [ "IResultCapture", "struct_catch_1_1_i_result_capture.html", null ],
      [ "IRunner", "struct_catch_1_1_i_runner.html", null ],
      [ "is_callable", "struct_catch_1_1is__callable.html", null ],
      [ "is_callable< Fun(Args...)>", "struct_catch_1_1is__callable_3_01_fun_07_args_8_8_8_08_4.html", null ],
      [ "is_callable_tester", "struct_catch_1_1is__callable__tester.html", null ],
      [ "is_range", "struct_catch_1_1is__range.html", null ],
      [ "IStream", "struct_catch_1_1_i_stream.html", null ],
      [ "ITestCaseRegistry", "struct_catch_1_1_i_test_case_registry.html", null ],
      [ "ITestInvoker", "struct_catch_1_1_i_test_invoker.html", null ],
      [ "ITransientExpression", "struct_catch_1_1_i_transient_expression.html", null ],
      [ "LazyExpression", "class_catch_1_1_lazy_expression.html", null ],
      [ "MatcherBase", "struct_catch_1_1_matcher_base.html", null ],
      [ "MatchExpr", "class_catch_1_1_match_expr.html", null ],
      [ "MessageBuilder", "struct_catch_1_1_message_builder.html", null ],
      [ "MessageInfo", "struct_catch_1_1_message_info.html", null ],
      [ "MessageStream", "struct_catch_1_1_message_stream.html", null ],
      [ "NameAndTags", "struct_catch_1_1_name_and_tags.html", null ],
      [ "NonCopyable", "class_catch_1_1_non_copyable.html", null ],
      [ "Option", "class_catch_1_1_option.html", null ],
      [ "pluralise", "struct_catch_1_1pluralise.html", null ],
      [ "RegistrarForTagAliases", "struct_catch_1_1_registrar_for_tag_aliases.html", null ],
      [ "ResultDisposition", "struct_catch_1_1_result_disposition.html", null ],
      [ "ResultWas", "struct_catch_1_1_result_was.html", null ],
      [ "ReusableStringStream", "class_catch_1_1_reusable_string_stream.html", null ],
      [ "RunTests", "struct_catch_1_1_run_tests.html", null ],
      [ "ScopedMessage", "class_catch_1_1_scoped_message.html", null ],
      [ "Section", "class_catch_1_1_section.html", null ],
      [ "SectionEndInfo", "struct_catch_1_1_section_end_info.html", null ],
      [ "SectionInfo", "struct_catch_1_1_section_info.html", null ],
      [ "ShowDurations", "struct_catch_1_1_show_durations.html", null ],
      [ "SimplePcg32", "class_catch_1_1_simple_pcg32.html", null ],
      [ "SourceLineInfo", "struct_catch_1_1_source_line_info.html", null ],
      [ "StreamEndStop", "struct_catch_1_1_stream_end_stop.html", null ],
      [ "StringMaker", "struct_catch_1_1_string_maker.html", null ],
      [ "StringMaker< bool >", "struct_catch_1_1_string_maker_3_01bool_01_4.html", null ],
      [ "StringMaker< Catch::Detail::Approx >", "struct_catch_1_1_string_maker_3_01_catch_1_1_detail_1_1_approx_01_4.html", null ],
      [ "StringMaker< char * >", "struct_catch_1_1_string_maker_3_01char_01_5_01_4.html", null ],
      [ "StringMaker< char >", "struct_catch_1_1_string_maker_3_01char_01_4.html", null ],
      [ "StringMaker< char const * >", "struct_catch_1_1_string_maker_3_01char_01const_01_5_01_4.html", null ],
      [ "StringMaker< char[SZ]>", "struct_catch_1_1_string_maker_3_01char_0f_s_z_0e_4.html", null ],
      [ "StringMaker< double >", "struct_catch_1_1_string_maker_3_01double_01_4.html", null ],
      [ "StringMaker< float >", "struct_catch_1_1_string_maker_3_01float_01_4.html", null ],
      [ "StringMaker< int >", "struct_catch_1_1_string_maker_3_01int_01_4.html", null ],
      [ "StringMaker< long >", "struct_catch_1_1_string_maker_3_01long_01_4.html", null ],
      [ "StringMaker< long long >", "struct_catch_1_1_string_maker_3_01long_01long_01_4.html", null ],
      [ "StringMaker< R C::* >", "struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4.html", null ],
      [ "StringMaker< R, typename std::enable_if< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value >::type >", "struct_catch_1_1_string_maker_3_01_r_00_01typename_01std_1_1enable__if_3_01is__range_3_01_r_01_4536d8fedfff6d62432b3dc59b56e1380.html", null ],
      [ "StringMaker< signed char >", "struct_catch_1_1_string_maker_3_01signed_01char_01_4.html", null ],
      [ "StringMaker< signed char[SZ]>", "struct_catch_1_1_string_maker_3_01signed_01char_0f_s_z_0e_4.html", null ],
      [ "StringMaker< std::nullptr_t >", "struct_catch_1_1_string_maker_3_01std_1_1nullptr__t_01_4.html", null ],
      [ "StringMaker< std::string >", "struct_catch_1_1_string_maker_3_01std_1_1string_01_4.html", null ],
      [ "StringMaker< std::wstring >", "struct_catch_1_1_string_maker_3_01std_1_1wstring_01_4.html", null ],
      [ "StringMaker< T * >", "struct_catch_1_1_string_maker_3_01_t_01_5_01_4.html", null ],
      [ "StringMaker< T[SZ]>", "struct_catch_1_1_string_maker_3_01_t_0f_s_z_0e_4.html", null ],
      [ "StringMaker< unsigned char >", "struct_catch_1_1_string_maker_3_01unsigned_01char_01_4.html", null ],
      [ "StringMaker< unsigned char[SZ]>", "struct_catch_1_1_string_maker_3_01unsigned_01char_0f_s_z_0e_4.html", null ],
      [ "StringMaker< unsigned int >", "struct_catch_1_1_string_maker_3_01unsigned_01int_01_4.html", null ],
      [ "StringMaker< unsigned long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01_4.html", null ],
      [ "StringMaker< unsigned long long >", "struct_catch_1_1_string_maker_3_01unsigned_01long_01long_01_4.html", null ],
      [ "StringMaker< wchar_t * >", "struct_catch_1_1_string_maker_3_01wchar__t_01_5_01_4.html", null ],
      [ "StringMaker< wchar_t const * >", "struct_catch_1_1_string_maker_3_01wchar__t_01const_01_5_01_4.html", null ],
      [ "StringRef", "class_catch_1_1_string_ref.html", null ],
      [ "TestCase", "class_catch_1_1_test_case.html", null ],
      [ "TestCaseInfo", "struct_catch_1_1_test_case_info.html", null ],
      [ "TestFailureException", "struct_catch_1_1_test_failure_exception.html", null ],
      [ "TestInvokerAsMethod", "class_catch_1_1_test_invoker_as_method.html", null ],
      [ "Timer", "class_catch_1_1_timer.html", null ],
      [ "Totals", "struct_catch_1_1_totals.html", null ],
      [ "true_given", "struct_catch_1_1true__given.html", null ],
      [ "UnaryExpr", "class_catch_1_1_unary_expr.html", null ],
      [ "UseColour", "struct_catch_1_1_use_colour.html", null ],
      [ "WaitForKeypress", "struct_catch_1_1_wait_for_keypress.html", null ],
      [ "WarnAbout", "struct_catch_1_1_warn_about.html", null ]
    ] ],
    [ "Approx", "class_approx.html", null ],
    [ "Catch_global_namespace_dummy", "struct_catch__global__namespace__dummy.html", null ],
    [ "DataBaseManager", "class_data_base_manager.html", "class_data_base_manager" ],
    [ "DataManager", "class_data_manager.html", null ],
    [ "HumiditySensor", "class_humidity_sensor.html", null ],
    [ "PressureSensor", "class_pressure_sensor.html", null ],
    [ "Sensor", "class_sensor.html", null ],
    [ "SensorList", "struct_sensor_list.html", null ],
    [ "SensorManager", "class_sensor_manager.html", "class_sensor_manager" ],
    [ "StatisticsManager", "class_statistics_manager.html", null ],
    [ "StatisticsReport", "struct_statistics_report.html", null ],
    [ "StatsData", "struct_stats_data.html", null ],
    [ "TempSensor", "class_temp_sensor.html", null ],
    [ "WeatherReport", "struct_weather_report.html", null ]
];